### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#127]
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/405

https://sentry.prod.mozaws.net/operations/firefox-connect/issues/4623385/

v1.0 top crasher: 36 crashes as recent as today. Looks like a platform issue.

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
    at com.amazon.alexa.AWA.webview.webViewClient.AWVAlexaWebViewClient.onPageFinished(AWVAlexaWebViewClient.java:11308)
    at com.amazon.webview.awvclients.AmazonWebViewClient.onPageFinished(AmazonWebViewClient.java:99)
    at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
    at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.onPageFinished(WebViewExtAmazonContentsClientAdapter.java:18)
    at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5597)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by mcomella** [comment]
Dupe #52.
