### ISSUE TITLE
Crash when navigating from settings About -> browser, or using url bar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#190]
## Steps to reproduce
- Open Firefox
- Visit a website
- Settings
- About

### Expected behavior
Shows About page on home screen

### Actual behavior
Crash

This is on master.

### Device information
* Echo Show device (1st gen? 2nd?): ?
* Firefox version: ?

```
    java.lang.IllegalStateException: Expected navigation overlay to exist
        at org.mozilla.focus.ScreenController.setNavigationOverlayIsVisible(ScreenController.kt:126)
        at org.mozilla.focus.MainActivity.setNavigationOverlayIsVisible(MainActivity.kt:170)
        at org.mozilla.focus.browser.BrowserFragmentCallbacks$DefaultImpls.setNavigationOverlayIsVisible$default(BrowserFragment.kt:48)
        at org.mozilla.focus.browser.BrowserFragment.loadUrl(BrowserFragment.kt:217)
        at org.mozilla.focus.ScreenController.showBrowserScreenForUrl(ScreenController.kt:85)
        at org.mozilla.focus.MainActivity.onValidBrowserIntent(MainActivity.kt:104)
        at org.mozilla.focus.MainActivity.access$onValidBrowserIntent(MainActivity.kt:44)
        at org.mozilla.focus.MainActivity$onNewIntent$1.invoke(MainActivity.kt:100)
        at org.mozilla.focus.MainActivity$onNewIntent$1.invoke(MainActivity.kt:44)
        at org.mozilla.focus.IntentValidator.validate(IntentValidator.kt:55)
        at org.mozilla.focus.MainActivity.onNewIntent(MainActivity.kt:100)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1308)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1320)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2968)
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:2983)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2999)
        at android.app.ActivityThread.-wrap14(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

We're calling something when we transition between screens.

**Comment by mcomella** [comment]
I see: we assume loadUrl can only be called when the navigation overlay is open – because we set nav overlay vis to gone and assume that only gets called when overlay vis is visible - which is not the case. This occurs:
- Loading pages from settings
- Loading values in the url bar
