### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'com.amazon.alexa.AWA.webview.state.StatusListener com.amazon.alexa.AWA.interrupt.a.b' on a null object reference

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#2]
https://sentry.prod.mozaws.net/operations/firefox-connect/issues/4690132/

We original saw this occurring, and fixed an issue, because we were creating two WebViews (the main one and the one in settings). However, we're still seeing this issue albeit infrequently.

Richard was able to reproduce this and iirc mentioned he saw this crash after he cleared data: maybe calling the WebView APIs in clear data is causing the crash.

There is also the possibility that the WebView is getting killed because we store it in the BrowserFragment and it disappears when switching activities.

```
java.lang.NullPointerException: Attempt to read from field 'com.amazon.alexa.AWA.webview.state.StatusListener com.amazon.alexa.AWA.interrupt.a.b' on a null object reference
    at com.amazon.alexa.AWA.webview.AlexaWebViewManager.onDestroy(AlexaWebViewManager.java:16060)
    at com.amazon.alexa.AWA.webview.WebViewLifecycleListener.onDestroy(WebViewLifecycleListener.java:48)
    at com.amazon.alexa.AWA.activity.a.onActivityDestroyed(LifecycleMonitor.java:91)
    at android.app.Application.dispatchActivityDestroyed(Application.java:245)
    at android.app.Activity.onDestroy(Activity.java:1654)
    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:382)
    at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
    at android.app.Activity.performDestroy(Activity.java:6228)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1157)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3898)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3929)
    at android.app.ActivityThread.access$1400(ActivityThread.java:160)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5597)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

java.lang.RuntimeException: Unable to destroy activity {org.mozilla.connect.firefox/org.mozilla.focus.settings.SettingsActivity}: java.lang.NullPointerException: Attempt to read from field 'com.amazon.alexa.AWA.webview.state.StatusListener com.amazon.alexa.AWA.interrupt.a.b' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3911)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3929)
    at android.app.ActivityThread.access$1400(ActivityThread.java:160)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5597)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by mcomella** [comment]
Closing in favor of non-migrated issue: https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/540
